// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOmbyWdKHFjpNMZOtdBXBCpn4ur20beew',
    appId: '1:969419659890:web:e8bfa2006c2fb01f0c80eb',
    messagingSenderId: '969419659890',
    projectId: 'message-board-app-cd8a1',
    authDomain: 'message-board-app-cd8a1.firebaseapp.com',
    storageBucket: 'message-board-app-cd8a1.firebasestorage.app',
    measurementId: 'G-1M5YSPZ1G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMinX7-7mT71AQ4yGxZzmspIchgw2HAuA',
    appId: '1:969419659890:android:5e3b3c3595a9a8720c80eb',
    messagingSenderId: '969419659890',
    projectId: 'message-board-app-cd8a1',
    storageBucket: 'message-board-app-cd8a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjocmOc3LudipnEYqTChXGrNsu0VdV6Ss',
    appId: '1:969419659890:ios:1d24a6fa12c4c1b00c80eb',
    messagingSenderId: '969419659890',
    projectId: 'message-board-app-cd8a1',
    storageBucket: 'message-board-app-cd8a1.firebasestorage.app',
    iosBundleId: 'com.example.hw02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjocmOc3LudipnEYqTChXGrNsu0VdV6Ss',
    appId: '1:969419659890:ios:1d24a6fa12c4c1b00c80eb',
    messagingSenderId: '969419659890',
    projectId: 'message-board-app-cd8a1',
    storageBucket: 'message-board-app-cd8a1.firebasestorage.app',
    iosBundleId: 'com.example.hw02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOmbyWdKHFjpNMZOtdBXBCpn4ur20beew',
    appId: '1:969419659890:web:aeb0be3c4ef81b1c0c80eb',
    messagingSenderId: '969419659890',
    projectId: 'message-board-app-cd8a1',
    authDomain: 'message-board-app-cd8a1.firebaseapp.com',
    storageBucket: 'message-board-app-cd8a1.firebasestorage.app',
    measurementId: 'G-GEKLLM65JP',
  );

}